### ISSUE TITLE
Mod SSL missing, MySQL password not set properly, Data Store Scopes, SSL verification for self-signed broken?

### ISSUE THREAD

**Issue by jsands-smc** [OCSInventory-NG/OCSInventory-Docker-Stack#13]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Docker host's operating system : Gentoo Linux

### Docker informations
Docker compose version :  1.27.4
Docker version : 19.03.14

### Problem's description
*Describe your problem here*

1)  mod_ssl is not installed in the default Docker image.   yum install mod_ssl and then apachectl -k restart allowed me to turn on and enforce SSL on the OCS admin panel, but that will not survive a reboot.

2)  Out of the box the MySQL password is not set properly everywhere (z-ocsinventory-server.conf).   This is not included in a data store by default so fixing this will not survive a reboot.

3)  It might be a good idea to change the scope of one of the default downloads data store.   It is /usr/share/ocsinventory-reports/ocsreports/downloads .... just moving that up one or two folders also puts into data store things you're absolutely going to want to be persistent ... like extensions in particular which are just one folder up.

4)  It is incredibly frustrating trying to get a self-signed certificate to work, but given all the stuff above in my way / complicating things that I'm hoping addressing some of these will make it easier to debug why self-signed certs flat out aren't working on any agent for me at this time.

**Comment by gillesdubois** [comment]
Hi @jsands-smc,

Please don't post issue on this repository it is not used anymore.
Please use this repository with our newer images / compse : https://github.com/OCSInventory-NG/OCSInventory-Docker-Image

You can also check out of wiki : http://wiki.ocsinventory-ng.org/13.Docker-documentation/Using-the-docker-image/

For example `/usr/share/ocsinventory-reports/ocsreports/downloads` doesn't exist anymore in the latest versions so you are certainly using a really old version of our product / image / etc..

However, to anwser your question about SSL : We don't provide SSL in the image even in the newer implementation. We decided to not implement SSL because in most of the case or users / customers have their own way to manage certificate or put OCS behind a reverse proxy that is providing the certificate.

We remain available if you want to open suggestion / an issue on our docker image repository.

I'll now be closing this issue.

Regards,
Gilles.
